replicaCount: 1

image:
  repository: localhost/metrics-gateway
  tag: "0.1.0"
  archiveSignature: ""
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8080

nodePort:
  enabled: true
  port: 8080
  nodePort: 30080

containerPort: 8080

metrics:
  cpu: slurm_job_cpu_load
  gpu: slurm_job_gpu_load
  memory: slurm_job_memory_load

serviceMonitor:
  enabled: true
  interval: 30s
  labels:
    release: monitoring
  monitoringLabel: metrics-gateway-monitor

podSecurityContext: {}

securityContext:
  runAsUser: 10001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
