apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metrics-gateway.fullname" . }}
  labels:
    {{- include "metrics-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "metrics-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        metrics-gateway/archive-signature: {{ .Values.image.archiveSignature | quote }}
      labels:
        {{- include "metrics-gateway.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: metrics-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
